CREATE TABLE IMOVEL (IMOVEL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
IMOVEL_RUA VARCHAR(255),
IMOVEL_NUMERO VARCHAR(255),
IMOVEL_BAIRRO VARCHAR(100),
IMOVEL_CEP VARCHAR(255),
IMOVEL_CIDADE VARCHAR(255),
IMOVEL_ESTADO VARCHAR(255),
IMOVEL_QTDVAGASGARAGEM VARCHAR(255),
IMOVEL_QTDDORMITORIOS VARCHAR(255), 
IMOVEL_TIPO VARCHAR(255),
IMOVEL_METROSQUADRADO VARCHAR(255),
IMOVEL_DESCRICAO VARCHAR(255));

