CREATE TABLE FUNCIONARIO (
FUNCIONARIO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FUNCIONARIO_NOME VARCHAR(255),
FUNCIONARIO_SOBRENOME VARCHAR(100),
FUNCIONARIO_CPF VARCHAR(100),
FUNCIONARIO_RG VARCHAR(255),
FUNCIONARIO_SEXO VARCHAR(255),
FUNCIONARIO_EMAIL VARCHAR(255),
FUNCIONARIO_NASCIMENTO VARCHAR(225),
FUNCIONARIO_FILIAL VARCHAR(100),
FUNCIONARIO_SENHA VARCHAR(100),
FUNCIONARIO_PERMISSAO VARCHAR(100),
FUNCIONARIO_CARGO VARCHAR(255));

INSERT
INTO
    `FUNCIONARIO`(
        `FUNCIONARIO_NOME`,
        `FUNCIONARIO_SOBRENOME`,
        `FUNCIONARIO_CPF`,
        `FUNCIONARIO_RG`,
        `FUNCIONARIO_SEXO`,
        `FUNCIONARIO_EMAIL`,
        `FUNCIONARIO_NASCIMENTO`,
        `FUNCIONARIO_FILIAL`,
        `FUNCIONARIO_SENHA`,
        `FUNCIONARIO_PERMISSAO`,
        `FUNCIONARIO_CARGO`
    )
VALUES(
    'Felipe',
    'Oliveira',
    '156.165.850-65',
    '15.987.805.-2',
    'Masculino',
    'felipe@aztec.com.br',
    '10/05/1980',
    'Filial Sul',
    '123456',
    'Admin',
    'Diretor'
)
