CREATE TABLE CONTRATO (
CONTRATO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CONTRATO_DATA VARCHAR(255),
/*DADOS DO CORRETOR*/
CONTRATO_FUNCIONARIO_ID INT,
CONTRATO_FUNCIONARIO_NOME VARCHAR(255),
CONTRATO_FUNCIONARIO_SOBRENOME VARCHAR(100),
CONTRATO_FUNCIONARIO_CPF VARCHAR(100),
CONTRATO_FUNCIONARIO_EMAIL VARCHAR(255),
CONTRATO_FUNCIONARIO_FILIAL VARCHAR(100),
/*DADOS DO CORRETOR*/
/*DADOS DO CLIENTE PROPRIETARIO*/
CONTRATO_CLIENTEPROPRIETARIO_PROPRIETARIO_ID INT,
CONTRATO_CLIENTEPROPRIETARIO_NOME VARCHAR(255), 
CONTRATO_CLIENTEPROPRIETARIO_SOBRENOME VARCHAR(255),
CONTRATO_CLIENTEPROPRIETARIO_CPF VARCHAR(100), 
CONTRATO_CLIENTEPROPRIETARIO_RG VARCHAR(255),
CONTRATO_CLIENTEPROPRIETARIO_EMAIL  VARCHAR(100),
CONTRATO_CLIENTEPROPRIETARIO_CELULAR VARCHAR(255),
CONTRATO_CLIENTEPROPRIETARIO_TELEFONE VARCHAR(255),
/*DADOS DO CLIENTE PROPRIETARIO*/
/*DADOS DO CLIENTE INTERESSADO*/
CONTRATO_CLIENTEINTERESSADO_ID INT,
CONTRATO_CLIENTEINTERESSADO_NOME VARCHAR(255), 
CONTRATO_CLIENTEINTERESSADO_SOBRENOME VARCHAR(255),
CONTRATO_CLIENTEINTERESSADO_CPF VARCHAR(100), 
CONTRATO_CLIENTEINTERESSADO_RG VARCHAR(255),
CONTRATO_CLIENTEINTERESSADO_EMAIL  VARCHAR(100),
CONTRATO_CLIENTEINTERESSADO_CELULAR VARCHAR(255),
CONTRATO_CLIENTEINTERESSADO_TELEFONE VARCHAR(255),
/*DADOS DO CLIENTE INTERESSADO*/
/*DADOS DO IMOVEL*/
CONTRATO_IMOVEL_ID INT,
CONTRATO_IMOVEL_RUA VARCHAR(255),
CONTRATO_IMOVEL_NUMERO VARCHAR(255),
CONTRATO_IMOVEL_COMPLEMENTO VARCHAR(255),
CONTRATO_IMOVEL_CEP VARCHAR(255),
CONTRATO_IMOVEL_BAIRRO VARCHAR(100),
CONTRATO_IMOVEL_CIDADE VARCHAR(255),
CONTRATO_IMOVEL_ESTADO VARCHAR(255),
CONTRATO_IMOVEL_TIPOTRANSACAO VARCHAR(255),
CONTRATO_IMOVEL_VLRVENDA VARCHAR (255),
CONTRATO_IMOVEL_VLRALUGUEL VARCHAR (255),
CONTRATO_IMOVEL_QTDVAGASGARAGEM VARCHAR(255),
CONTRATO_IMOVEL_QTDDORMITORIOS VARCHAR(255), 
CONTRATO_IMOVEL_TIPO VARCHAR(255),
CONTRATO_IMOVEL_METROSQUADRADO VARCHAR(255),
CONTRATO_IMOVEL_DESCRICAO VARCHAR(255)
/*DADOS DO IMOVEL*/

);




