CREATE TABLE FUNCIONARIO (
FUNCIONARIO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(255),
CPF_FUNCIONARIO VARCHAR(100),
SEXO_FUNCIONARIO VARCHAR(255),
EMAIL_FUNCIONARIO VARCHAR(255),
SENHA_FUNCIONARIO VARCHAR(255),
NASCIMENTO_FUNCIONARIO VARCHAR(225),
CARGO_FUNCIONARIO VARCHAR(255));

INSERT
INTO
    `funcionario`(
        `NOME_FUNCIONARIO`,
        `CPF_FUNCIONARIO`,
        `SEXO_FUNCIONARIO`,
        `EMAIL_FUNCIONARIO`,
        `SENHA_FUNCIONARIO`,
        `NASCIMENTO_FUNCIONARIO`,
        `CARGO_FUNCIONARIO`
    )
VALUES(
    'Rafael Oliveira',
    '400.300.200-12',
    'Masculino',
    'rafael@aztec.com.br',
    '123456',
    '10/05/1980',
    'Corretor'
)

